workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      groups:
        - signing-android
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Flutter analyze
        script: flutter analyze

      - name: Flutter unit tests
        script: flutter test

      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.aab
